export const social_url = [
  {
    social_name: "LinkedIn",
    url: "https://www.linkedin.com/in/arajankit/",
  },
  {
    social_name: "Medium",
    url: "https://medium.com/@arajAnkit",
  },
  {
    social_name: "Twitter",
    url: "https://twitter.com/araj_ankit",
  },
  {
    social_name: "GitHub",
    url: "https://github.com/arajAnkit",
  },
  {
    social_name: "LeetCode",
    url: "https://leetcode.com/arajAnkit/",
  },
];

export const Skill_data = [
  {
    skill_name: "C",
    Image: "/c.png",
    width: 80,
    height: 80,
    docsUrl: "https://devdocs.io/c/",
  },
  {
    skill_name: "Python",
    Image: "/python.png",
    width: 65,
    height: 65,
    docsUrl: "https://www.python.org/",
  },
  {
    skill_name: "Cpp",
    Image: "/cpp.png",
    width: 80,
    height: 80,
    docsUrl: "https://cplusplus.com/doc/tutorial/",
  },
  {
    skill_name: "SQL",
    Image: "/sql.png",
    width: 70,
    height: 70,
    docsUrl: "https://www.w3schools.com/sql/",
  },
  {
    skill_name: "Git",
    Image: "/git.png",
    width: 80,
    height: 80,
    docsUrl: "https://git-scm.com/",
  },
  {
    skill_name: "GitHub",
    Image: "/github.png",
    width: 70,
    height: 70,
    docsUrl: "https://github.com/",
  },
  {
    skill_name: "Linux",
    Image: "/linux.png",
    width: 70,
    height: 70,
    docsUrl: "https://www.linux.org/",
  },
  {
    skill_name: "Auth Js",
    Image: "/authjs.webp",
    width: 70,
    height: 70,
    docsUrl: "https://authjs.dev/",
  },
  {
    skill_name: "Clerk",
    Image: "/clerk.svg",
    width: 70,
    height: 70,
    docsUrl: "https://clerk.com/",
  },
  {
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 75,
    height: 75,
    docsUrl: "https://www.framer.com/motion/",
  },
  {
    skill_name: "Bun",
    Image: "/bun.png",
    width: 80,
    height: 80,
    docsUrl: "https://bun.sh/",
  },
  {
    skill_name: "Webhook",
    Image: "/webhook.png",
    width: 80,
    height: 80,
    docsUrl: "https://docs.github.com/en/webhooks",
  },
  {
    skill_name: "Ubuntu",
    Image: "/ubuntu.png",
    width: 80,
    height: 80,
    docsUrl: "https://ubuntu.com/",
  },
  {
    skill_name: "GitLab",
    Image: "/gitlab.png",
    width: 75,
    height: 75,
    docsUrl: "https://about.gitlab.com/",
  },
];

export const Frontend_skill = [
  {
    skill_name: "Html",
    Image: "/html.png",
    width: 65,
    height: 65,
    docsUrl: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  {
    skill_name: "Css",
    Image: "/css.png",
    width: 80,
    height: 80,
    docsUrl: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  {
    skill_name: "Java Script",
    Image: "/js.png",
    width: 65,
    height: 65,
    docsUrl: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  {
    skill_name: "Tailwind Css",
    Image: "/tailwind.png",
    width: 80,
    height: 80,
    docsUrl: "https://tailwindcss.com/",
  },
  {
    skill_name: "Vite",
    Image: "/vite.png",
    width: 80,
    height: 80,
    docsUrl: "https://vitejs.dev/",
  },
  {
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    height: 80,
    docsUrl: "https://react.dev/",
  },
  {
    skill_name: "Redux",
    Image: "/redux.png",
    width: 80,
    height: 80,
    docsUrl: "https://redux.js.org/",
  },
  {
    skill_name: "Next",
    Image: "/nextjs.svg",
    width: 85,
    height: 85,
    docsUrl: "https://nextjs.org/",
  },
  {
    skill_name: "Type Script",
    Image: "/ts.png",
    width: 70,
    height: 70,
    docsUrl: "https://www.typescriptlang.org/",
  },
  {
    skill_name: "Shadcn UI",
    Image: "/shadcn.png",
    width: 70,
    height: 70,
    docsUrl: "https://ui.shadcn.com/",
  },
  {
    skill_name: "Next UI",
    Image: "/nextui.png",
    width: 70,
    height: 70,
    docsUrl: "https://nextui.org/",
  },
];

export const Backend_skill = [
  {
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    height: 80,
    docsUrl: "https://nodejs.org/en",
  },
  {
    skill_name: "Express js",
    Image: "/express.png",
    width: 80,
    height: 80,
    docsUrl: "https://expressjs.com/",
  },
  {
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 40,
    height: 40,
    docsUrl: "https://www.mongodb.com/",
  },
  {
    skill_name: "Fire base",
    Image: "/Firebase.png",
    width: 55,
    height: 55,
    docsUrl: "https://firebase.google.com/",
  },
  {
    skill_name: "Postgre SQL",
    Image: "/postger.png",
    width: 70,
    height: 70,
    docsUrl: "https://www.postgresql.org/",
  },
  {
    skill_name: "My SQL",
    Image: "/mysql.png",
    width: 70,
    height: 70,
    docsUrl: "https://www.mysql.com/",
  },
  {
    skill_name: "Prisma",
    Image: "/prisma.webp",
    width: 70,
    height: 70,
    docsUrl: "https://www.prisma.io/",
  },
  {
    skill_name: "Graphql",
    Image: "/graphql.png",
    width: 80,
    height: 80,
    docsUrl: "https://graphql.org/",
  },
  {
    skill_name: "Drizzle",
    Image: "/drizzle.png",
    width: 80,
    height: 80,
    docsUrl: "https://orm.drizzle.team/",
  },
  {
    skill_name: "Redis",
    Image: "/redis.png",
    width: 100,
    height: 100,
    docsUrl: "https://redis.io/",
  },
];

export const Full_stack = [
  {
    skill_name: "React Native",
    Image: "/ReactNative .png",
    width: 70,
    height: 70,
    docsUrl: "https://reactnative.dev/",
  },
  {
    skill_name: "Expo",
    Image: "/expo.png",
    width: 70,
    height: 70,
    docsUrl: "https://expo.dev/",
  },
  {
    skill_name: "Docker",
    Image: "/docker.webp",
    width: 70,
    height: 70,
    docsUrl: "https://www.docker.com/",
  },
  {
    skill_name: "Figma",
    Image: "/figma.png",
    width: 50,
    height: 50,
    docsUrl: "https://www.figma.com/",
  },
  {
    skill_name: "Material Ui",
    Image: "/mui.png",
    width: 80,
    height: 80,
    docsUrl: "https://mui.com/material-ui/",
  },
];

export const Other_skill = [
  {
    skill_name: "AWS",
    Image: "/aws.png",
    width: 60,
    height: 60,
    docsUrl: "https://aws.amazon.com/",
  },
  {
    skill_name: "Vercel",
    Image: "/vercel.png",
    width: 60,
    height: 60,
    docsUrl: "https://vercel.com/",
  },
  {
    skill_name: "Digital Ocean",
    Image: "/digitalocean.png",
    width: 55,
    height: 50,
    docsUrl: "https://www.digitalocean.com/",
  },
];
